import type { Category, Product, Order, Retailer, AppNotification } from './types'

export const categories: Category[] = [
  { id: 'grains', name: 'Grains & Cereals', emoji: '🌾', bgColor: '#D97706', active: true },
  { id: 'oils', name: 'Edible Oils', emoji: '🫙', bgColor: '#EA580C', active: true },
  { id: 'pulses', name: 'Pulses & Lentils', emoji: '🫘', bgColor: '#0D9488', active: true },
  { id: 'spices', name: 'Spices & Masala', emoji: '🌶️', bgColor: '#7C3AED', active: true },
  { id: 'dairy', name: 'Dairy Products', emoji: '🥛', bgColor: '#DB2777', active: true },
  { id: 'bakery', name: 'Bakery', emoji: '🍞', bgColor: '#92400E', active: true },
  { id: 'beverages', name: 'Beverages', emoji: '🧃', bgColor: '#2563EB', active: true },
  { id: 'cleaning', name: 'Cleaning Supplies', emoji: '🧹', bgColor: '#DC2626', active: true },
]

export const products: Product[] = [
  {
    id: 'rice-25', name: 'Basmati Rice Premium 25kg', categoryId: 'grains', unit: 'kg',
    price: 68,
    priceTiers: [
      { label: 'Below 240g', price: 75 },
      { label: '240g – 999g', price: 70 },
      { label: '1kg – 2.4kg', price: 68 },
      { label: 'Above 2.4kg', price: 65 },
    ],
    stock: 320, emoji: '🌾', active: true,
    description: 'Premium long-grain basmati rice, aged 2 years for superior aroma and fluffiness. Ideal for wholesale kitchens and retail distribution.',
  },
  {
    id: 'wheat-50', name: 'Whole Wheat Flour 50kg', categoryId: 'grains', unit: 'kg',
    price: 32,
    priceTiers: [{ label: 'Standard rate', price: 32 }],
    stock: 180, emoji: '🌾', active: true,
    description: 'Stone-ground whole wheat flour rich in fiber. Perfect for chapati, roti, and commercial baking.',
  },
  {
    id: 'brown-rice', name: 'Brown Rice 25kg', categoryId: 'grains', unit: 'kg',
    price: 55,
    priceTiers: [{ label: 'Standard rate', price: 55 }],
    stock: 45, emoji: '🍚', active: true,
    description: 'Unpolished brown rice with natural bran layer intact. High in fiber and nutrients.',
  },
  {
    id: 'sunflower-15', name: 'Sunflower Oil 15L Tin', categoryId: 'oils', unit: 'tin',
    price: 1850,
    priceTiers: [{ label: 'Per tin', price: 1850 }],
    stock: 42, emoji: '🫙', active: true,
    description: 'Refined sunflower oil, cold-pressed for wholesale kitchens and retail resale. Rich in Vitamin E, low cholesterol. Sealed tin, 15-litre capacity.',
  },
  {
    id: 'groundnut-15', name: 'Groundnut Oil 15L Tin', categoryId: 'oils', unit: 'tin',
    price: 2150,
    priceTiers: [{ label: 'Per tin', price: 2150 }],
    stock: 28, emoji: '🫙', active: true,
    description: 'Cold-pressed groundnut oil with natural aroma and rich flavor. Ideal for deep frying and everyday cooking.',
  },
  {
    id: 'mustard-5', name: 'Mustard Oil 5L Can', categoryId: 'oils', unit: 'can',
    price: 720,
    priceTiers: [{ label: 'Per can', price: 720 }],
    stock: 15, emoji: '🫙', active: true,
    description: 'Kachi ghani mustard oil with pungent aroma. Popular in North Indian and Bengali cuisines.',
  },
  {
    id: 'coconut-1', name: 'Coconut Oil 1L Pouch', categoryId: 'oils', unit: 'pouch',
    price: 210,
    priceTiers: [{ label: 'Per pouch', price: 210 }],
    stock: 85, emoji: '🥥', active: true,
    description: 'Pure coconut oil for cooking and personal care. Light texture, rich in medium-chain fatty acids.',
  },
  {
    id: 'toor-dal', name: 'Toor Dal 25kg', categoryId: 'pulses', unit: 'kg',
    price: 120,
    priceTiers: [{ label: 'Standard rate', price: 120 }],
    stock: 8, emoji: '🫘', active: true,
    description: 'Premium arhar/toor dal, clean and polished. Ideal for dal tadka and sambar preparations.',
  },
  {
    id: 'chana-dal', name: 'Chana Dal 25kg', categoryId: 'pulses', unit: 'kg',
    price: 95,
    priceTiers: [{ label: 'Standard rate', price: 95 }],
    stock: 22, emoji: '🫘', active: true,
    description: 'Split bengal gram, rich in protein. Used for dal, snacks, and traditional sweets.',
  },
  {
    id: 'moong-dal', name: 'Moong Dal 10kg', categoryId: 'pulses', unit: 'kg',
    price: 105,
    priceTiers: [{ label: 'Standard rate', price: 105 }],
    stock: 35, emoji: '🫘', active: true,
    description: 'Yellow split moong dal, light and easily digestible. Great for dal and khichdi.',
  },
  {
    id: 'turmeric', name: 'Turmeric Powder 1kg', categoryId: 'spices', unit: 'kg',
    price: 145,
    priceTiers: [{ label: 'Standard rate', price: 145 }],
    stock: 60, emoji: '🌿', active: true,
    description: 'Pure turmeric powder with high curcumin content. Vibrant color and strong medicinal aroma.',
  },
  {
    id: 'red-chilli', name: 'Red Chilli Powder 1kg', categoryId: 'spices', unit: 'kg',
    price: 210,
    priceTiers: [{ label: 'Standard rate', price: 210 }],
    stock: 45, emoji: '🌶️', active: true,
    description: 'Medium-hot blend of Kashmiri and Guntur red chilli. Bright color with robust heat.',
  },
  {
    id: 'ghee-15', name: 'Pure Cow Ghee 15kg', categoryId: 'dairy', unit: 'kg',
    price: 580,
    priceTiers: [{ label: 'Standard rate', price: 580 }],
    stock: 25, emoji: '🧈', active: true,
    description: 'Clarified butter from pure cow milk. Rich golden color, high smoke point, authentic flavor.',
  },
  {
    id: 'tea-25', name: 'CTC Tea 25kg', categoryId: 'beverages', unit: 'kg',
    price: 280,
    priceTiers: [{ label: 'Standard rate', price: 280 }],
    stock: 55, emoji: '🍵', active: true,
    description: 'Premium CTC tea for strong chai. Excellent color and brisk taste.',
  },
  {
    id: 'sugar-50', name: 'Refined Sugar 50kg', categoryId: 'beverages', unit: 'kg',
    price: 42,
    priceTiers: [{ label: 'Standard rate', price: 42 }],
    stock: 200, emoji: '🍬', active: true,
    description: 'Double-refined white sugar, consistent crystal size. Standard grade for retail and food service.',
  },
  {
    id: 'detergent-5', name: 'Washing Powder 5kg', categoryId: 'cleaning', unit: 'pack',
    price: 340,
    priceTiers: [{ label: 'Per pack', price: 340 }],
    stock: 70, emoji: '🧺', active: true,
    description: 'High-lather washing powder for commercial laundry and retail sale.',
  },
]

export const orders: Order[] = [
  {
    id: '8F3C21',
    retailerId: 'sharma',
    retailerName: 'Sharma General Store',
    items: [
      { productId: 'rice-25', name: 'Basmati Rice 25kg × 1', qty: 1, unit: 'kg', unitPrice: 1700, total: 1700 },
      { productId: 'sunflower-15', name: 'Sunflower Oil 15L × 1', qty: 1, unit: 'tin', unitPrice: 1850, total: 1850 },
      { productId: 'toor-dal', name: 'Toor Dal · 1.2 kg @ ₹120/kg', qty: 1, unit: 'kg', unitPrice: 144, total: 144 },
    ],
    subtotal: 3694,
    deliveryCharge: 80,
    total: 3774,
    status: 'out-for-delivery',
    date: '12 Aug 2026',
    address: 'MG Road, Shop No. 14, Pune, 411001',
    payment: 'Cash on Delivery',
    paid: false,
  },
  {
    id: '4E9A02',
    retailerId: 'patil',
    retailerName: 'Patil Kirana Store',
    items: [
      { productId: 'wheat-50', name: 'Wheat Flour 50kg × 1', qty: 1, unit: 'kg', unitPrice: 1600, total: 1600 },
      { productId: 'mustard-5', name: 'Mustard Oil 5L × 1', qty: 1, unit: 'can', unitPrice: 720, total: 720 },
    ],
    subtotal: 2320,
    deliveryCharge: 65,
    total: 2385,
    status: 'pending',
    date: '12 Aug 2026',
    address: 'Shivaji Nagar, Pune 411005',
    payment: 'UPI',
    paid: false,
  },
  {
    id: '7A1D09',
    retailerId: 'sharma',
    retailerName: 'Sharma General Store',
    items: [
      { productId: 'rice-25', name: 'Basmati Rice 25kg × 1', qty: 1, unit: 'kg', unitPrice: 1700, total: 1700 },
      { productId: 'groundnut-15', name: 'Groundnut Oil 15L × 1', qty: 1, unit: 'tin', unitPrice: 2150, total: 2150 },
    ],
    subtotal: 3850,
    deliveryCharge: 75,
    total: 3925,
    status: 'delivered',
    date: '04 Aug 2026',
    address: 'MG Road, Shop No. 14, Pune, 411001',
    payment: 'Cash on Delivery',
    paid: true,
  },
  {
    id: '6C4B77',
    retailerId: 'sharma',
    retailerName: 'Sharma General Store',
    items: [
      { productId: 'chana-dal', name: 'Chana Dal 25kg × 1', qty: 1, unit: 'kg', unitPrice: 2375, total: 2375 },
    ],
    subtotal: 2375,
    deliveryCharge: 70,
    total: 2445,
    status: 'cancelled',
    date: '28 Jul 2026',
    address: 'MG Road, Shop No. 14, Pune, 411001',
    payment: 'UPI',
    paid: false,
  },
  {
    id: 'A2B4C8',
    retailerId: 'modern',
    retailerName: 'Modern Traders',
    items: [
      { productId: 'sunflower-15', name: 'Sunflower Oil 15L × 2', qty: 2, unit: 'tin', unitPrice: 1850, total: 3700 },
      { productId: 'sugar-50', name: 'Refined Sugar 50kg × 1', qty: 1, unit: 'kg', unitPrice: 2100, total: 2100 },
    ],
    subtotal: 5800,
    deliveryCharge: 90,
    total: 5890,
    status: 'confirmed',
    date: '11 Aug 2026',
    address: 'Kothrud Main Road, Shop 7, Pune, 411038',
    payment: 'UPI',
    paid: true,
  },
]

export const retailers: Retailer[] = [
  {
    id: 'sharma', name: 'Sharma General Store', owner: 'Ramesh Sharma',
    phone: '98765 43210', email: 'ramesh@sharmastore.com',
    address: 'MG Road, Shop No. 14', city: 'Pune', pincode: '411001',
    gst: '27ABCDE1234F1Z5', hours: '09:00 AM – 09:00 PM',
    accountHolder: 'Ramesh Sharma', accountNo: 'XXXXXXXX4521',
    ifsc: 'HDFC0001234', bankName: 'HDFC Bank',
    registeredOn: '15 Mar 2025', status: 'approved', totalSpend: 28450, orderCount: 12,
  },
  {
    id: 'modern', name: 'Modern Traders', owner: 'Anita Deshmukh',
    phone: '97654 32109', email: 'anita@moderntraders.com',
    address: 'Kothrud Main Road, Shop 7', city: 'Pune', pincode: '411038',
    gst: '27FGHIJ5678K2Y6', hours: '08:00 AM – 08:00 PM',
    accountHolder: 'Anita Deshmukh', accountNo: 'XXXXXXXX8832',
    ifsc: 'ICIC0002345', bankName: 'ICICI Bank',
    registeredOn: '02 Jan 2025', status: 'approved', totalSpend: 14020, orderCount: 6,
  },
  {
    id: 'verma-approved', name: 'Sunrise Kirana', owner: 'Priya Verma',
    phone: '88776 55443', email: 'priya@sunrisekirana.com',
    address: 'FC Road, Shop 3', city: 'Pune', pincode: '411004',
    gst: '27KLMNO9012P3Q7', hours: '07:00 AM – 09:00 PM',
    accountHolder: 'Priya Verma', accountNo: 'XXXXXXXX6612',
    ifsc: 'PUNB0003344', bankName: 'Punjab National Bank',
    registeredOn: '10 Jun 2025', status: 'approved', totalSpend: 9870, orderCount: 5,
  },
  {
    id: 'patil', name: 'Patil Kirana Store', owner: 'Sunil Patil',
    phone: '90211 22334', email: 'sunil.patil@example.com',
    address: 'Shivaji Nagar', city: 'Pune', pincode: '411005',
    gst: '27PQRSX5678L1Z2', hours: '09:00 AM – 09:00 PM',
    accountHolder: 'Sunil Patil', accountNo: 'XXXXXXXX7789',
    ifsc: 'IBKL0001122', bankName: 'Indian Bank',
    registeredOn: '10 Aug 2026', status: 'pending', totalSpend: 0, orderCount: 0,
  },
  {
    id: 'verma', name: 'Verma Wholesale', owner: 'Deepak Verma',
    phone: '88990 11223', email: 'deepak@vermawholesale.com',
    address: 'Hadapsar Industrial Estate, A-12', city: 'Pune', pincode: '411028',
    gst: '', hours: '07:00 AM – 07:00 PM',
    accountHolder: 'Deepak Verma', accountNo: 'XXXXXXXX3345',
    ifsc: 'IBKL0001122', bankName: 'IDBI Bank',
    registeredOn: '09 Aug 2026', status: 'pending', totalSpend: 0, orderCount: 0,
  },
  {
    id: 'nirmala', name: 'Nirmala Provision Store', owner: 'Nirmala Joshi',
    phone: '99887 76655', email: 'nirmala@gmail.com',
    address: 'Deccan Gymkhana', city: 'Pune', pincode: '411004',
    gst: '', hours: '10:00 AM – 08:00 PM',
    accountHolder: 'Nirmala Joshi', accountNo: 'XXXXXXXX3344',
    ifsc: 'SBIN0002233', bankName: 'State Bank of India',
    registeredOn: '09 Aug 2026', status: 'pending', totalSpend: 0, orderCount: 0,
  },
  {
    id: 'raj', name: 'Raj Mart', owner: 'Rajesh Kumar',
    phone: '87654 32101', email: 'raj@rajmart.com',
    address: 'Camp Area, Shop 22', city: 'Pune', pincode: '411001',
    gst: '', hours: '08:00 AM – 10:00 PM',
    accountHolder: 'Rajesh Kumar', accountNo: 'XXXXXXXX6677',
    ifsc: 'PUNB0003344', bankName: 'Punjab National Bank',
    registeredOn: '08 Aug 2026', status: 'pending', totalSpend: 0, orderCount: 0,
  },
]

export const notifications: AppNotification[] = [
  { id: '1', title: 'Order Confirmed', body: 'Your order #8F3C21 has been confirmed by the admin.', time: '2h ago', read: false },
  { id: '2', title: 'Low Stock Alert', body: 'Toor Dal is running low on stock at Jyoti Traders.', time: '5h ago', read: false },
  { id: '3', title: 'Order Delivered', body: 'Order #7A1D09 has been delivered to your store.', time: '1d ago', read: true },
  { id: '4', title: 'Welcome to Jyoti Traders', body: 'Your account has been approved. Start shopping now.', time: '3d ago', read: true },
]

export const weeklyOrders = [8, 12, 6, 15, 10, 18, 9]
export const weekDays = ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun']

export const CURRENT_RETAILER = 'sharma'
